### ISSUE TITLE
Trying to run Laradumps inside WSL2

### ISSUE THREAD

**Issue by zacktagnan** [laradumps/laradumps#185]
Hi ... I just install Laradumps inside a Laravel project but, when I open the Laradumps APP, there is no project loaded.

I am on Windows 11 with WSL2. I have installed VSCode inside Windows.

Executing the following command inside Powershell:
```
|> wsl -l -v
NAME      STATE           VERSION
Ubuntu    Running         2
```

Inside this Ubuntu, I have installed Docker Engine with Docker Compose.
I have the WSL extension on VSCode to be able to open the project inside the Ubuntu of WSL.
On Ubuntu, my project is on: /home/my_user/www/my_project

First, I have installed the LaraDumps Desktop for Windows.
After that, I have installed the package with this command for Laravel:
composer require laradumps/laradumps ^3.0 --dev -W

Using Laravel Sail on my project to run, for example, Composer, I excute the command like this:
`sail composer require laradumps/laradumps ^3.0 --dev -W`
And the package has been installed.

For having the "laradumps.yaml" configuration file on the root project, finally, I have to execute the init command like this:
`|> vendor/bin/laradumps init`
The others ways to execute it don't work for me (like `sail artisan ds:init $(pwd)`).

Watching the WSL section on package Configuration, I have make some modifications on my "laradumps.yaml" configuration file and that's its current content:

```
app:
  primary_host: 172.19.80.1
  secondary_host: host.docker.internal
  port: 9191
  workdir: /var/www/html/
  project_path: /home/zroot/www/lvl-modular-components/
  wsl_config: wsl+Ubuntu/
config:
  sleep: 0
  macos_auto_launch: false
observers:
  auto_invoke_app: false
  enabled_in_testing: false
xdebug:
  client_host: 0.0.0.0
  client_port: 9003
code_snippet:
  above: 9
  below: 3
```

When it's running, the URL project is "http://localhost:7000". The port on "laradumps.yaml" is refered to LaraDumps Desktop or it has to be refered to the project port, so, 7000?

Despite everything configured, the package still doesn't work.
Could I get some advice on how to get everything working as desired and be able to use this package for project debugging?

**Comment by ChrisToxz** [comment]
Is the `primary_host` correct?
Did you try to `ds()` something in your app and run it? Only then it will popup as a project in Laradumps.

`The others ways to execute it don't work for me (like sail artisan ds:init $(pwd)).`
Why it doens't work, what error?

**Comment by dougkusanagi** [comment]
I'm having a similar problem and i used to use laradumps in the same setup as on this project.
I have installed laradumps app in windows and the composer package in a laravel 11 project inside WSL2 but without sail (not relavant but i use valet for linux package)
It doesn't throw any errors when i use `ds()` helper function but it doesn't show nothing in the windows app neither.

laradumps.yaml
```yaml
app:
    primary_host: 127.0.0.1
    secondary_host: host.docker.internal
    port: 9191
    workdir: /var/www/html/
    project_path: /home/silver/sites/guepardo/
    wsl_config: wsl+Ubuntu/
config:
    sleep: 0
    macos_auto_launch: false
observers:
    auto_invoke_app: false
    enabled_in_testing: false
    dump: false
    original_dump: true
    queries: false
    slow_queries: false
    mail: false
    logs: false
    http: false
    jobs: false
    commands: false
    scheduled_commands: false
    gate: false
    cache: false
xdebug:
    client_host: 0.0.0.0
    client_port: 9003
code_snippet:
    above: 9
    below: 3
logs:
    info: false
    warning: false
    emergency: false
    alert: false
    debug: false
    error: true
    critical: true
    notice: true
    vendor: false
    deprecated_message: false
slow_queries:
    threshold_in_ms: 500
queries:
    only_duplicated: false
    select: true
    insert: true
    update: true
    delete: true

```
